name_unique:
  appproto_name:
  - '-'
  - dns
  - modbus
  - ''
  - ssl
  - http
  - dhcp
  - ssh
  origstate_name:
  - OTH
  - S1
  - S0
  - SF
  - ''
  - RSTO
  - REJ
  proto_name:
  - icmp
  - tcp
  - udp
  - ARP
